---
type: widget_page
---

## Estudio de Percepciones de Seguridad y Policías en Chile (2023 - 2024).

El Estudio de Percepciones de Seguridad y Policías de Chile (ESEP), diseñado por el Observatorio de Violencia y Legitimidad Social, tiene como objetivo conocer las percepciones de la ciudadanía sobre la delincuencia en el país y la manera en que las personas se vinculan con las policías.

El estudio fue concebido originalmente como una encuesta longitudinal, en la que las y los participantes reportarían sus actitudes de manera regular para comprender cómo evolucionan estos fenómenos en el tiempo. La muestra objetivo incluye hombres y mujeres de entre 18 y 65 años, residentes en zonas urbanas del país, seleccionados mediante un muestreo probabilístico polietápico.

Este estudio se encuentra financiado por la Universidad Diego Portales y la Agencia Nacional de Investigación y Desarrollo (ANID) a través de los fondos Fondecyt Regular N. 1221805 y ANID Exploración N. 13220187. Además, la recopilación de datos fue realizado por la consultora Statcom Datavoz. El estudio es dirigido por la [Dra. Monica Gerber](https://oles2.netlify.app/author/monica-m.-gerber/), profesora titular de la Facultad de Psicología de la Universidad Diego Portales.

Para más información, se recomienda acceder al [sitio web de ESEP](https://esep.netlify.app/)

## Ola 0 (Reclutamiento)

<div style="display: flex; justify-content: center;">
  <iframe width="800" height="400" marginheight="0" marginwidth="0" src="https://olescl.quarto.pub/prealas-esep/#/title-slide"></iframe>
</div>


La ola de reclutamiento (Ola 0) se llevó a cabo entre junio de 2023 y febrero de 2024, mediante entrevistas presenciales en todo el país, con el fin de conformar un panel inicial de participantes. El trabajo de campo, realizado por la consultora Statcom Datavoz, permitió reunir 5.304 casos representativos de la población urbana nacional.
Si bien el diseño contemplaba la realización de mediciones posteriores al mismo grupo de personas, por el momento solo se ha completado la ola de reclutamiento.
Para conocer los resultados y la metodología de esta primera medición, puede descargar el reporte en el siguiente enlace:

Para conocer los resultados y especificidades metodológicas de la ola 0, el usuario puede descargar el reporte de la ola haciendo click en el botón a continuación.

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Botón Informe</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <a href="https://raw.githack.com/oles-cl/esep_presentations/main/report/w0_report.pdf" class="report-button" download>
        <svg class="icon" xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24">
            <path d="M0 0h24v24H0z" fill="none"/>
            <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm3 15h-6v-2h6v2zm0-4h-6v-2h6v2zm0-4h-6V7h6v2z"/>
        </svg>
        Descargar Reporte ESEP ola 0
    </a>

    <p><strong>Advertencia:</strong> ESEP no prosperó como una encuesta longitudinal y los datos obtenidos solo corresponden al reclutamiento. El Estudio Panel de Percepciones de Seguridad y Policías en Chile (EPSEP) iniciado desde noviembre 2024 y ha finalizar en enero de 2026 consideró una diseño longitudinal, aunque con muestras y técnicas recolección distintas </p>
</body>
</html>
