## Encuesta de Legitimidad de Carabineros. Violencia, Derechos Humanos y Control Social (2021 - 2022)

En el año 2021 y 2022 OLES llevó a cabo una encuesta longitudinal de tipo panel busca analizar el cambio en las percepciones, actitudes y creencias en torno a la vinculación entre Carabineros de Chile y la ciudadanía. En particular, se realizó una medición sistemática en tres periodos de tiempo, lo cual permite comprender la evolución de la legitimidad de Carabineros, así como evaluar los antecedentes y consecuencias de dicha legitimidad. Más específicamente, la encuesta busca alcanzar los siguientes objetivos:

-   Medir de manera sistemática en el tiempo las percepciones de legitimidad de Carabineros de Chile.
-   Evaluar el efecto de las percepciones de justicia en el trato y los procedimientos utilizados por Carabineros al interactuar con la ciudadanía en:
    -   La percepción de legitimidad de los mismos.
    -   La percepción de legitimidad de la institución policial.
    -   La justificación de la violencia como forma de reivindicar derechos por parte de manifestantes.
    
Para acceder a la base de datos de este estudio, y orientar su manipulación, se recomienda utilizar el manual metodológico escrito por las y los integrantes de OLES:

<html>
  <head>
    <title>Manual Metodologico</title>
    <style>
      body {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
      }

      .button {
        display: inline-block;
        padding: 4px 10px;
        text-align: left;
        text-decoration: none;
        color: #ffffff;
        background-color: #9D44C0;
        border-radius: 4px;
        outline: none;
        transition: 0.3s;
        border: 2px solid transparent;
      }

      .button:hover,
      .button:focus {
        background-color: #c2c7c7;
        border-color: #7aa8b7;
      }

      .icon {
        margin-right: 5px; /* Add some space between the icon and text */
      }
    </style>
  </head>
  <body>
    <a class="button" href="https://nicolastobarj.quarto.pub/manual_encuesta_oles/" aria-label="Learn about the HTML button tag" target="_blank">
      <span class="icon"></span>
      <span>Ver Manual Metodológico Encuesta de Legitimidad de Carabineros 2021-2022</span>
    </a>
  </body>
</html>
