---
title: "Dra. Macarena Orchard imparte seminario doctoral acerda de sus estudios sobre respeto"
authors: [bruno_r]
date: 2024-07-22T21:13:14-05:00
categories: ["Noticias"]
tags: ["Noticias"]
image:
  caption: 'Fuente de imagen: UPLA'
  focal_point: Right
---

En el marco del doctorado en Ciencias sociales de la Universidad de Playa Ancha, en el curso “Análisis y discusión de metodologías de investigación en Ciencias Sociales” dictado por la académica Claudia Carrasco y David Miranda, la investigadora OLES Macarena Orchard (UDP) presentó un seminario sobre la metodología de uno de sus más recientes estudios: “El estudio sociológico del respeto, desde un enfoque metodológico mixto”.

La investigadora OLES compartió con los estudiantes el proceso metodológico que comenzó su tesis de doctorado hasta su proyecto Fondecyt «Mi tesis es un análisis sobre los significados del respeto en la sociedad chilena. Intentando construir una perspectiva teórica al problema del respeto en términos sociológicos, siendo un tema clave en la sociedad chilena donde las demandas por respeto se han hecho visibles».

De la misma forma la profesora destacó el feedback que recibió de sus colegas y estudiantes durante el seminario «Hubo una buena participación de los estudiantes, pude conocer de sus proyectos de tesis y apoyarlos en pensar aristas de sus problemas de investigación. Fue agradable la participación de académicos, con los que pude conversar y recibir feedback, lo que siempre es un placer». 
